main: com.rayzr522.stafflogin.StaffLogin
name: StaffLogin
version: 1.1.0
description: Forces staff to have to log in before they can move or do anything.
author: Rayzr
commands:
  login:
    description: Log in as staff
    usage: "/login <password>"
    permission: StaffLogin.require
  logout:
    description: Log out
    usage: "/logout"
    permission: StaffLogin.require
  password:
    description: Set your password
    usage: "/password <password>"
    permission: StaffLogin.require
